### ISSUE TITLE
pitch project ideas

### ISSUE THREAD

**Issue by Faucherie** [Faucherie/cm2020_midterm#1]

**Comment by dabogdan** [comment]
I suggest a Vocation Finder App: the app that suggests which career path to take based on the users' preferences & answers. 

Mobile and Web App.

**Comment by dabogdan** [comment]
My other idea is related to the blockchain. We could use this API that I developed and build the frontend & mobile app for it: https://github.com/dabogdan/disperse-collect

**Comment by GanWenHaoIsaac** [comment]
I'm down for the Web App, but I wanna hear what everyone thinks first

**Comment by Faucherie** [comment]
Some formalizations are thoughts for a networking app where a series has multiple events and no people repeat from event 
to event during a series. https://github.com/Faucherie/Roundtable-app

**Comment by Faucherie** [comment]
The Final Pitches:
1. Expand Dmytro Bogdan original project of matching UoL CS students with possible careers Use 
2. Dmytro Bogdan blockchain code to disperse ETH and ERC20 tokens and build a front end.
3. Elshad Data vis project for currency exchange
4. Scott network project
